services:
  - type: web
    name: svar-rasotsav-2026
    env: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
